defmodule Blog.Post do
  @moduledoc """
  A multilingual post. Everything search-related is declared by the single
  `search do … end` block — the `search_text` column, the keep-in-sync change, the GIN
  index and the `:search` read action are all generated by the `SearchAsh` extension.
  """
  use Ash.Resource,
    otp_app: :blog,
    domain: Blog.Blog,
    data_layer: AshPostgres.DataLayer,
    extensions: [SearchAsh]

  postgres do
    table "posts"
    repo Blog.Repo
  end

  # Attribute-based multitenancy: every read is automatically scoped to the org set
  # via `tenant:`. Search composes with this — a tenant only ever sees its own rows.
  multitenancy do
    strategy :attribute
    attribute :org_id
    # Allow tenant-less reads (e.g. the GreenAsh admin console). Isolation still applies
    # whenever a tenant IS given — the app/API always passes one.
    global? true
  end

  search do
    fields [:title, :body]
    language_attribute :language
  end

  actions do
    defaults [:read]

    create :create do
      accept [:title, :body, :language]
    end
  end

  attributes do
    uuid_primary_key :id
    attribute :org_id, :string, allow_nil?: false, public?: true
    attribute :title, :string, allow_nil?: false, public?: true
    attribute :body, :string, allow_nil?: false, public?: true

    attribute :language, :atom,
      allow_nil?: false,
      public?: true,
      constraints: [one_of: Stemmers.supported_languages()]

    timestamps()
  end
end
