defmodule SearchAsh.Changes.SyncSearchText do
  @moduledoc """
  Global change generated by `SearchAsh`. On create/update it recomputes the
  `search_text` attribute from the configured `fields`, stemmed in the row's language
  via `SearchCore`. Runs in `before_action` so it sees final attribute values.
  """
  use Ash.Resource.Change

  @impl true
  def change(changeset, _opts, _context) do
    resource = changeset.resource
    fields = SearchAsh.Info.fields(resource)
    language_attribute = SearchAsh.Info.language_attribute(resource)
    search_text_attribute = SearchAsh.Info.search_text_attribute(resource)

    Ash.Changeset.before_action(changeset, fn changeset ->
      case Ash.Changeset.get_attribute(changeset, language_attribute) do
        nil ->
          changeset

        language ->
          text =
            fields
            |> Enum.map(&to_string(Ash.Changeset.get_attribute(changeset, &1) || ""))
            |> Enum.join(" ")

          Ash.Changeset.force_change_attribute(
            changeset,
            search_text_attribute,
            SearchCore.searchable_text(text, language)
          )
      end
    end)
  end
end
