defmodule SearchAsh.Changes.SyncSearchText do
  @moduledoc """
  Global change generated by `SearchAsh`. Keeps the `search_text` attribute in sync with
  the configured `fields`, stemmed in the row's language via `SearchCore`.

  It only recomputes when it needs to — on create, or on an update that actually changes
  a search field or the language — so unrelated updates skip the stemmer entirely. It
  never recomputes from partially-loaded data: if a search field isn't loaded (e.g. an
  update issued with a narrowed `select`), it leaves the existing `search_text` intact
  rather than dropping that field's content from the index.
  """
  use Ash.Resource.Change

  @impl true
  def change(changeset, _opts, _context) do
    resource = changeset.resource
    fields = SearchAsh.Info.fields(resource)
    language_attribute = SearchAsh.Info.language_attribute(resource)
    search_text_attribute = SearchAsh.Info.search_text_attribute(resource)

    if recompute?(changeset, fields, language_attribute) do
      Ash.Changeset.before_action(
        changeset,
        &sync(&1, fields, language_attribute, search_text_attribute)
      )
    else
      changeset
    end
  end

  defp recompute?(changeset, fields, language_attribute) do
    changeset.action_type == :create or
      Enum.any?([language_attribute | fields], &Ash.Changeset.changing_attribute?(changeset, &1))
  end

  defp sync(changeset, fields, language_attribute, search_text_attribute) do
    language = Ash.Changeset.get_attribute(changeset, language_attribute)
    values = Enum.map(fields, &Ash.Changeset.get_attribute(changeset, &1))

    cond do
      Enum.any?([language | values], &match?(%Ash.NotLoaded{}, &1)) ->
        # A needed attribute isn't loaded — don't recompute from partial data.
        changeset

      is_nil(language) ->
        changeset

      true ->
        text = values |> Enum.map(&to_string(&1 || "")) |> Enum.join(" ")

        Ash.Changeset.force_change_attribute(
          changeset,
          search_text_attribute,
          SearchCore.searchable_text(text, language)
        )
    end
  end
end
