defmodule SearchAsh.Source.Changes.Remove do
  @moduledoc false
  # On destroy: either remove the source record's index row (`on_destroy: :remove`, hard
  # delete) or keep it flagged archived (`on_destroy: :archive`, soft delete via a destroy
  # action such as AshArchival).
  #
  # Like the sync change, this touches no source attribute, so `atomic/3` returns `:ok` and
  # bulk destroy can use the default `:atomic_batches` strategy, mirroring each destroyed
  # record in `after_batch/3`. Single-record destroys run through `change/3`; because
  # `change/3` is defined, `after_batch/3` is not also wired into the single path.
  #
  # Notifications from the index writes are returned up through the hooks so Ash can
  # dispatch them at the transaction boundary (otherwise they'd be reported as "missed").
  use Ash.Resource.Change

  alias SearchAsh.Source.{Document, Index}

  @impl true
  def change(changeset, _opts, _context) do
    Ash.Changeset.after_action(changeset, fn changeset, record ->
      case apply_destroy(changeset.resource, record, changeset.tenant) do
        [] -> {:ok, record}
        notifications -> {:ok, record, notifications}
      end
    end)
  end

  @impl true
  def atomic(_changeset, _opts, _context), do: :ok

  @impl true
  def after_batch(changesets_and_records, _opts, _context) do
    Enum.flat_map(changesets_and_records, fn {changeset, record} ->
      notifications = apply_destroy(changeset.resource, record, changeset.tenant)
      [{:ok, record} | notifications]
    end)
  end

  # Returns the notifications generated by the index write(s). The record is only needed to
  # derive its `source_id` — everything past that point works from `(source_type, source_id)`
  # in `Source.Index`, which is what lets `SearchAsh.reindex_one/3` run the same `on_destroy`
  # logic for a source that is already gone.
  defp apply_destroy(resource, record, tenant) do
    source_id = Document.source_id(resource, record)
    {_result, notifications} = Index.apply_destroy(resource, source_id, tenant)
    notifications
  end
end
