defmodule SearchAsh.Source.Changes.Remove do
  @moduledoc false
  # On destroy: either remove the source record's index row (`on_destroy: :remove`, hard
  # delete) or keep it flagged archived (`on_destroy: :archive`, soft delete via a destroy
  # action such as AshArchival).
  #
  # Like the sync change, this touches no source attribute, so `atomic/3` returns `:ok` and
  # bulk destroy can use the default `:atomic_batches` strategy, mirroring each destroyed
  # record in `after_batch/3`. Single-record destroys run through `change/3`; because
  # `change/3` is defined, `after_batch/3` is not also wired into the single path.
  #
  # Notifications from the index writes are returned up through the hooks so Ash can
  # dispatch them at the transaction boundary (otherwise they'd be reported as "missed").
  use Ash.Resource.Change
  require Ash.Query

  alias SearchAsh.Source.{Document, Info}

  @impl true
  def change(changeset, _opts, _context) do
    Ash.Changeset.after_action(changeset, fn changeset, record ->
      case apply_destroy(changeset.resource, record, changeset.tenant) do
        [] -> {:ok, record}
        notifications -> {:ok, record, notifications}
      end
    end)
  end

  @impl true
  def atomic(_changeset, _opts, _context), do: :ok

  @impl true
  def after_batch(changesets_and_records, _opts, _context) do
    Enum.flat_map(changesets_and_records, fn {changeset, record} ->
      notifications = apply_destroy(changeset.resource, record, changeset.tenant)
      [{:ok, record} | notifications]
    end)
  end

  # Returns the notifications generated by the index write(s).
  defp apply_destroy(resource, record, tenant) do
    case Info.on_destroy(resource) do
      :archive -> archive(resource, record, tenant)
      _remove -> remove(resource, record, tenant)
    end
  end

  defp remove(resource, record, tenant) do
    index = Info.index(resource)
    source_type = Info.source_type(resource)
    source_id = Document.source_id(resource, record)

    index
    |> Ash.Query.filter(source_type == ^source_type and source_id == ^source_id)
    |> Ash.read!(tenant: tenant)
    |> Enum.flat_map(&Ash.destroy!(&1, tenant: tenant, return_notifications?: true))
  end

  # Flip `archived` on the existing index row(s), reusing the row's own already-stemmed
  # values rather than rebuilding the document from the source record: it avoids re-running
  # the stemmer on a destroy and doesn't depend on the source record's searchable fields
  # being loaded. If nothing is indexed for this source, there's nothing to hide — no-op.
  defp archive(resource, record, tenant) do
    index = Info.index(resource)
    source_type = Info.source_type(resource)
    source_id = Document.source_id(resource, record)

    index
    |> Ash.Query.filter(source_type == ^source_type and source_id == ^source_id)
    |> Ash.read!(tenant: tenant)
    |> Enum.flat_map(fn row ->
      {_indexed, notifications} =
        index
        |> Ash.Changeset.for_create(:upsert, archived_attrs(row), tenant: tenant)
        |> Ash.create!(return_notifications?: true)

      notifications
    end)
  end

  defp archived_attrs(row) do
    %{
      source_type: row.source_type,
      source_id: row.source_id,
      language: row.language,
      search_text: row.search_text,
      label: row.label,
      archived: true
    }
  end
end
