defmodule SearchAsh.Preparations.Search do
  @moduledoc """
  Preparation generated by `SearchAsh` for the `:search` read action. Builds a
  tsquery from the `query` + `language` arguments (same `SearchCore` pipeline used at
  index time) and filters on the `'simple'` tsvector of the search-text column.
  """
  use Ash.Resource.Preparation
  require Ash.Query

  @impl true
  def prepare(query, _opts, _context) do
    resource = query.resource
    search_text_attribute = SearchAsh.Info.search_text_attribute(resource)
    term = Ash.Query.get_argument(query, :query)
    language = normalize_language(Ash.Query.get_argument(query, :language), resource)
    # Branch on the *computed* tsquery: a short (< min_length) or all-stopwords query
    # yields no tokens ("") even when the term is non-blank.
    tsquery = if is_binary(term), do: SearchCore.tsquery(term, language), else: ""

    if tsquery == "" do
      # Nothing searchable → no filter, so a list UI shows all rows before you type.
      query
    else
      Ash.Query.filter(
        query,
        fragment(
          "to_tsvector('simple', ?) @@ to_tsquery('simple', ?)",
          ^ref(search_text_attribute),
          ^tsquery
        )
      )
    end
  end

  defp normalize_language(lang, _resource) when is_atom(lang) and not is_nil(lang), do: lang
  defp normalize_language(_lang, resource), do: SearchAsh.Info.default_language(resource)
end
