defmodule SearchAsh.Preparations.Search do
  @moduledoc """
  Preparation generated by `SearchAsh` for the `:search` read action. Builds a
  tsquery from the `query` + `language` arguments (same `SearchCore` pipeline used at
  index time) and filters on the `'simple'` tsvector of the search-text column.
  """
  use Ash.Resource.Preparation
  require Ash.Query

  @impl true
  def prepare(query, _opts, _context) do
    resource = query.resource
    search_text_attribute = SearchAsh.Info.search_text_attribute(resource)
    term = Ash.Query.get_argument(query, :query)
    language = normalize_language(Ash.Query.get_argument(query, :language), resource)
    # Branch on the *computed* tsquery: a short (< min_length) or all-stopwords query
    # yields no tokens ("") even when the term is non-blank.
    tsquery =
      if is_binary(term),
        do: SearchCore.tsquery(term, language, prefix: SearchAsh.Info.prefix?(resource)),
        else: ""

    query
    |> maybe_filter(search_text_attribute, tsquery)
    |> apply_rank(SearchAsh.Info.rank?(resource), tsquery)
  end

  # Blank/short query → no filter, so a list UI shows all rows before you type.
  defp maybe_filter(query, _search_text_attribute, ""), do: query

  defp maybe_filter(query, search_text_attribute, tsquery) do
    Ash.Query.filter(
      query,
      fragment(
        "to_tsvector('simple', ?) @@ to_tsquery('simple', ?)",
        ^ref(search_text_attribute),
        ^tsquery
      )
    )
  end

  # Rank and expose `:search_rank` only when there is an actual query. A blank query
  # (list-all) is returned unranked and does NOT load `:search_rank` — check
  # `Ash.Resource.loaded?(row, :search_rank)` if you display it.
  defp apply_rank(query, false, _tsquery), do: query
  defp apply_rank(query, true, ""), do: query

  defp apply_rank(query, true, tsquery) do
    query
    |> Ash.Query.load(search_rank: %{tsquery: tsquery})
    |> Ash.Query.sort(search_rank: {%{tsquery: tsquery}, :desc})
  end

  # Fall back to the resource's default language for anything that isn't a supported
  # Stemmers language (nil, a non-atom, or an unknown atom) — never crash the stemmer.
  defp normalize_language(lang, resource) do
    if is_atom(lang) and Stemmers.supported?(lang) do
      lang
    else
      SearchAsh.Info.default_language(resource)
    end
  end
end
