defmodule SearchAsh.Preparations.Search do
  @moduledoc """
  Preparation generated by `SearchAsh` for the `:search` read action. Builds a
  tsquery from the `query` + `language` arguments (same `SearchCore` pipeline used at
  index time) and filters on the `'simple'` tsvector of the search-text column.
  """
  use Ash.Resource.Preparation
  require Ash.Query

  @impl true
  def prepare(query, _opts, _context) do
    resource = query.resource
    search_text_attribute = SearchAsh.Info.search_text_attribute(resource)
    term = Ash.Query.get_argument(query, :query)
    language = Ash.Query.get_argument(query, :language) || SearchAsh.Info.default_language(resource)

    if is_binary(term) and String.trim(term) != "" do
      tsquery = SearchCore.tsquery(term, language)

      Ash.Query.filter(
        query,
        fragment(
          "to_tsvector('simple', ?) @@ to_tsquery('simple', ?)",
          ^ref(search_text_attribute),
          ^tsquery
        )
      )
    else
      # Blank query: no filter, so a list UI shows all rows before you type.
      query
    end
  end
end
