defmodule Blog.Repo.Migrations.GlobalSearch do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:search_documents, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :text, null: false)
      add(:source_type, :text, null: false)
      add(:source_id, :text, null: false)
      add(:language, :text, null: false)
      add(:search_text, :text, null: false)
      add(:label, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      index(:search_documents, ["(to_tsvector('simple', search_text))"],
        name: "search_documents_search_idx",
        using: "gin"
      )
    )

    create(
      unique_index(:search_documents, [:org_id, :source_type, :source_id],
        name: "search_documents_unique_source_index"
      )
    )

    create table(:produits, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :text, null: false)
      add(:reference, :text, null: false)
      add(:libelle, :text, null: false)
      add(:description, :text)
      add(:language, :text, null: false, default: "french")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:factures, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :text, null: false)
      add(:numero, :text, null: false)
      add(:client_nom, :text)
      add(:description, :text)
      add(:language, :text, null: false, default: "french")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create table(:clients, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :text, null: false)
      add(:nom, :text, null: false)
      add(:email, :text)
      add(:notes, :text)
      add(:language, :text, null: false, default: "french")

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(table(:clients))

    drop(table(:factures))

    drop(table(:produits))

    drop_if_exists(
      unique_index(:search_documents, [:org_id, :source_type, :source_id],
        name: "search_documents_unique_source_index"
      )
    )

    drop_if_exists(
      index(:search_documents, ["(to_tsvector('simple', search_text))"],
        name: "search_documents_search_idx"
      )
    )

    drop(table(:search_documents))
  end
end
