defmodule SearchDemo.Repo.Migrations.SearchV040 do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists(
      index(:search_documents, ["(to_tsvector('simple', search_text))"],
        name: "search_documents_search_idx"
      )
    )

    alter table(:search_documents) do
      add(:excerpt, :text)
      add(:label_normalized, :text)
      add(:document_date, :date)
    end

    create index(:search_documents, ["(search_text::tsvector)"],
             name: "search_documents_search_idx",
             using: "gin"
           )

    create index(:search_documents, ["label_normalized gin_trgm_ops"],
             name: "search_documents_label_trgm_idx",
             using: "gin"
           )

    drop_if_exists(
      index(:posts, ["(to_tsvector('simple', search_text))"], name: "posts_search_idx")
    )

    create index(:posts, ["(search_text::tsvector)"], name: "posts_search_idx", using: "gin")

    alter table(:factures) do
      add(:date_emission, :date)
    end

    create table(:facture_lignes, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :text, null: false)

      add(
        :facture_id,
        references(:factures,
          column: :id,
          name: "facture_lignes_facture_id_fkey",
          type: :uuid,
          prefix: "public"
        ), null: false)

      add(:designation, :text)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end

  def down do
    drop(constraint(:facture_lignes, "facture_lignes_facture_id_fkey"))

    drop(table(:facture_lignes))

    alter table(:factures) do
      remove(:date_emission)
    end

    drop_if_exists(index(:posts, ["(search_text::tsvector)"], name: "posts_search_idx"))

    create index(:posts, ["(to_tsvector('simple', search_text))"],
             name: "posts_search_idx",
             using: "gin"
           )

    drop_if_exists(
      index(:search_documents, ["label_normalized gin_trgm_ops"],
        name: "search_documents_label_trgm_idx"
      )
    )

    drop_if_exists(
      index(:search_documents, ["(search_text::tsvector)"], name: "search_documents_search_idx")
    )

    alter table(:search_documents) do
      remove(:document_date)
      remove(:label_normalized)
      remove(:excerpt)
    end

    create index(:search_documents, ["(to_tsvector('simple', search_text))"],
             name: "search_documents_search_idx",
             using: "gin"
           )
  end
end
