defmodule SearchDemo.Repo.Migrations.ArchivedFlag do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:search_documents) do
      remove(:state)
      add(:archived, :boolean, null: false, default: false)
    end
  end

  def down do
    alter table(:search_documents) do
      remove(:archived)
      add(:state, :text, null: false, default: "active")
    end
  end
end
