defmodule SearchDemo.Repo.Migrations.StatutKeyword do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:search_documents) do
      add(:statut, :text)
    end

    alter table(:factures) do
      add(:statut, :text, null: false, default: "brouillon")
    end
  end

  def down do
    alter table(:factures) do
      remove(:statut)
    end

    alter table(:search_documents) do
      remove(:statut)
    end
  end
end
