defmodule SearchDemo.Repo.Migrations.CreatePosts do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:posts, primary_key: false) do
      add(:search_text, :text)
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :text, null: false)
      add(:title, :text, null: false)
      add(:body, :text, null: false)
      add(:language, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end

    create(
      index(:posts, ["(to_tsvector('simple', search_text))"],
        name: "posts_search_idx",
        using: "gin"
      )
    )
  end

  def down do
    drop_if_exists(
      index(:posts, ["(to_tsvector('simple', search_text))"], name: "posts_search_idx")
    )

    drop(table(:posts))
  end
end
