defmodule SearchDemo.Repo.Migrations.TagsEtMontants do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:search_documents) do
      add(:tags, {:array, :text})
      add(:montant, :decimal)
    end

    alter table(:factures) do
      add(:tags, {:array, :text})
      add(:montant, :decimal)
    end
  end

  def down do
    alter table(:factures) do
      remove(:montant)
      remove(:tags)
    end

    alter table(:search_documents) do
      remove(:montant)
      remove(:tags)
    end
  end
end
