defmodule SearchDemo.Repo.Migrations.IsoLanguageCodes do
  @moduledoc """
  search_ash 0.2.0 accepts ISO 639-1 codes only, so `:french` becomes `:fr`.

  The column-default changes were autogenerated with
  `mix ash_postgres.generate_migrations`; the data backfill below was added by hand and is
  the part that matters — **generate_migrations cannot write it for you**. Existing rows
  still hold `'french'`, which 0.2.0 can no longer cast back into an atom, so reading them
  would fail until they are rewritten. Copy this shape for your own tables.
  """

  use Ecto.Migration

  # Every table holding a language, including the search index itself.
  @tables [:posts, :produits, :factures, :clients, :search_documents]

  # Only the languages this app actually used. A wider mapping is unnecessary: any code
  # already in ISO form is left alone.
  @renames [{"french", "fr"}, {"english", "en"}]

  def up do
    alter table(:produits) do
      modify(:language, :text, default: "fr")
    end

    alter table(:factures) do
      modify(:language, :text, default: "fr")
    end

    alter table(:clients) do
      modify(:language, :text, default: "fr")
    end

    backfill(@renames)
  end

  def down do
    alter table(:clients) do
      modify(:language, :text, default: "french")
    end

    alter table(:factures) do
      modify(:language, :text, default: "french")
    end

    alter table(:produits) do
      modify(:language, :text, default: "french")
    end

    backfill(Enum.map(@renames, fn {from, to} -> {to, from} end))
  end

  defp backfill(renames) do
    for table <- @tables, {from, to} <- renames do
      execute("UPDATE #{table} SET language = '#{to}' WHERE language = '#{from}'")
    end
  end
end
