defmodule SearchDemo.Repo.Migrations.DemoUsers do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:users, primary_key: false) do
      add(:id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true)
      add(:org_id, :text, null: false)
      add(:nom, :text, null: false)
      add(:role, :text, null: false, default: "support")
    end
  end

  def down do
    drop(table(:users))
  end
end
