defmodule SearchDemo.Repo.Migrations.UseGlobalIndexExtension do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:search_documents) do
      remove(:updated_at)
      remove(:inserted_at)
      modify(:search_text, :text, null: true)
      add(:state, :text, null: false, default: "active")
    end
  end

  def down do
    alter table(:search_documents) do
      remove(:state)
      modify(:search_text, :text, null: false)

      add(:inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )

      add(:updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
      )
    end
  end
end
